### ISSUE TITLE
Can't create a checkbox inside th.

### ISSUE THREAD

**Issue by ifti24** [alalonde/angular-scrollable-table#43]
Tried to create a checkbox inside the **'th'**  but failed.
`<th sortable-header col="facility">Facility
       <input type='checkbox' />
</th>`

**Comment by alalonde** [comment]
You should be able to play around with the CSS to get this to work.  In order to support the auto-ellipsis feature (one of our core features), we set the label display to `block`, which pushes any other content to the next line (past the fixed height of the element).

See here for an easy CSS tweak to get something like this to work: https://jsfiddle.net/alalonde/0qaf46k6/
